### ISSUE TITLE
Update principles

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer-site#10]
@csuwildcat Loved the principles you seeded, and thought that there was some overlap between "Individual Empowerment" and "Self-Ownership" - both have a theme of returning power to users.

So I've changed "Individual Empowerment" to:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/199891/161912168-a2380a67-1ed7-4cc7-a021-560776862482.png">

Will commit here but if you disagree let's discuss and we can roll back if need be.

**Comment by thereisnogabe** [comment]
I feel the previous text better reflected our work
