### ISSUE TITLE
Mobile view shows wrapping

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer-site#7]
![Image from iOS](https://user-images.githubusercontent.com/199891/161644869-4143c6b0-8a5a-4009-a640-198d99432b85.jpg)

@csuwildcat Any ideas?

**Comment by csuwildcat** [comment]
I'll throw a white-space: nowrap on it tonight

**Comment by mistermoe** [comment]
@csuwildcat fixed this yesterday. closing it out
